Update Dockerfile
update to fix the following error - 
The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'lemur-web' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa -y &&   apt-get update &&   apt-get install -y curl git build-essential sudo     python3.6 python3-pip python3.6-dev     nodejs npm     postgresql postgresql-contrib     libpq-dev libssl-dev libffi-dev libsasl2-dev libldap2-dev &&   ln -sf /usr/bin/python3.6 /usr/local/bin/python3 &&   update-alternatives --install /usr/bin/python python /usr/bin/python3 1 &&   update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 &&   update-alternatives --install /usr/bin/node node /usr/bin/nodejs 1 &&   apt-get clean -y &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100